version: '3.8'

services: 
  node_backend:
    container_name: express_sequelize
    image: express_sequelize:0.0.4
    build: 
      context: .
    ports:
      - "3001:3001"
    environment: 
      - EXTERNAL_PORT=3001
      - PGDATABASE=postgres_db
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGHOST=node_db
    depends_on: 
      - node_db
  node_db: 
    container_name: node_db
    image: "postgres:13"
    ports:
      - "54321:5432"
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres_db
    volumes:
      - nps_data:/var/lib/postgresql/data

volumes:
  nps_data: {}